# This is the final, correct code for your workflow file.
name: JobNimbus Activity to Google Chat

on:
  workflow_dispatch:
    inputs:
      activity_note:
        description: 'The full text of the JobNimbus activity note'
        required: true
        default: 'Document Created | N/A | Unknown User | Unknown Job | 2025-08-02T12:00:00Z'
      job_number:
        description: 'The JobNimbus ID for the related job'
        required: false
        default: '1164'

jobs:
  build_and_send_notification:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Parse the incoming note text to extract details
      - name: Parse Activity Note
        number: parser
        run: |
          # The note text is received as a single string, e.g., "Document Created | Proposal Created | Reina Toledo ..."
          # We use the pipe '|' as a delimiter to split it into parts
          IFS='|' read -ra parts <<< "${{ github.event.inputs.activity_note }}"

          # Trim whitespace from each part and assign to a variable
          activity_type=$(echo "${parts[0]}" | xargs)
          document_type=$(echo "${parts[1]}" | xargs)
          user_name=$(echo "${parts[2]}" | xargs)
          
          # Output each piece of data so it can be used in later steps
          echo "activity_type=${activity_type}" >> $GITHUB_ENV
          echo "document_type=${document_type}" >> $GITHUB_ENV
          echo "user_name=${user_name}" >> $GITHUB_ENV

      # Step 2: Send the formatted notification to Google Chat
      - name: Send to Google Chat
        uses: peter-evans/webhook-action@v2
        with:
          url: ${{ secrets.GCHAT_WEBHOOK_URL }}
          payload: |
            {
              "cards": [
                {
                  "header": {
                    "title": "${{ env.activity_type }}",
                    "subtitle": "Activity Logged by: ${{ env.user_name }}",
                    "imageUrl": "https://ik.imagekit.io/roosterroofing/Untitled%20design%20(13).png?updatedAt=1752077429449",
                    "imageStyle": "IMAGE"
                  },
                  "sections": [
                    {
                      "widgets": [
                        {
                          "decoratedText": {
                            "topLabel": "Document Type",
                            "text": "${{ env.document_type }}"
                          }
                        },
                        {
                          "buttons": [
                            {
                              "textButton": {
                                "text": "VIEW JOB IN JOBNIMBUS",
                                "onClick": {
                                  "openLink": {
                                    "url": "https://app.jobnimbus.com/job/${{ github.event.inputs.job_id }}"
                                  }
                                }
                              }
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
