name: Notify Google Chat on Material Confirmation Update

on:
  workflow_dispatch:
    inputs:
      contact_name:
        description: 'The display name of the primary contact'
        required: true
      job_address:
        description: 'The first line of the job address'
        required: true
      document_link:
        description: 'A direct URL to the created document'
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Node.js script with received data
        run: |
          # This script is a placeholder to demonstrate passing data.
          # In a real scenario, your main script would read these env vars.
          echo "Received contact: ${{ github.event.inputs.contact_name }}"
          echo "Received address: ${{ github.event.inputs.job_address }}"

      - name: Send Google Chat Notification
        uses: peter-evans/webhook-action@v2
        with:
          url: ${{ secrets.GCHAT_WEBHOOK_URL }}
          payload-file: .github/workflows/gchat-payload.json
          payload: |
            {
              "cards": [
                {
                  "header": {
                    "title": "Confirmation of Materials Document Created",
                    "subtitle": "${{ github.event.inputs.contact_name }} – ${{ github.event.inputs.job_address }}",
                    "imageUrl": "https://ik.imagekit.io/roosterroofing/Untitled%20design%20(13).png?updatedAt=1752077429449",
                    "imageStyle": "IMAGE"
                  },
                  "sections": [
                    {
                      "widgets": [
                        {
                          "textParagraph": {
                            "text": "The <b>Confirmation of Materials</b> document for this job has progressed. See status below:<br><br>✔️ Document Created<br>📤 Document Sent<br>✍️ Document Signed"
                          }
                        },
                        {
                          "buttons": [
                            {
                              "textButton": {
                                "text": "VIEW DOCUMENT",
                                "onClick": {
                                  "openLink": {
                                    "url": "${{ github.event.inputs.document_link }}"
                                  }
                                }
                              }
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
