name: JobNimbus Activity to Google Chat

on:
  repository_dispatch:
    types: [jobnimbus_generic_activity]

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Generic Notification to Google Chat
        uses: peter-evans/webhook-action@v2
        with:
          url: ${{ secrets.GCHAT_WEBHOOK_URL }}
          payload: |
            {
              "cards": [
                {
                  "header": {
                    "title": "New Activity in JobNimbus",
                    "subtitle": "An automated activity was logged.",
                    "imageUrl": "https://ik.imagekit.io/roosterroofing/Untitled%20design%20(13).png?updatedAt=1752077429449",
                    "imageStyle": "IMAGE"
                  },
                  "sections": [
                    {
                      "widgets": [
                        {
                          "textParagraph": {
                            "text": "A document-related activity (Created, Signed, etc.) has occurred. Please check the JobNimbus dashboard for details."
                          }
                        },
                        {
                          "buttons": [
                            {
                              "textButton": {
                                "text": "OPEN JOBNIMBUS",
                                "onClick": {
                                  "openLink": {
                                    "url": "https://app.jobnimbus.com/"
                                  }
                                }
                              }
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
